name: "Felipe Fronchetti"
occupation: "Master's Student in Computer Science"
university: "University of São Paulo"
email: "fronchetti@usp.br"
photography: "imgs/profile.jpg"
biography: "Fronchetti is a Master's Degree student in Computer Science at the University of São Paulo (USP), Brazil.
            His research lies in the intersection between Software Engineering (SE) and Computer Supported Cooperative Work (CSCW). 
            He is co-(author) of 8 papers in top tier journals and conferences on Software Engineering, 
            working on the supporting of newcomers in Open Source Software communities."

collections:
  papers:
  degrees:
  awards:
  fundings:
  extensions:
  tools: